// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.680
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html><head><script src=\"https://cdnjs.cloudflare.com/ajax/libs/pocketbase/0.21.2/pocketbase.umd.js\"></script><script type=\"text/javascript\">\r\n\t\t\t\tconst pb = new PocketBase(\"http://127.0.0.1:8090\")\r\n\t\t\t\t\r\n\t\t\t\tasync function login() {\r\n\t\t\t\t\tconst username = document.getElementById('username').value\r\n\t\t\t\t\tconst password = document.getElementById('password').value\r\n\t\t\t\t\tconst authData = await pb.collection('users').authWithPassword(username, password)\r\n\t\t\t\t\tconsole.log(pb.authStore.isValid);\r\n\t\t\t\t\tconsole.log(pb.authStore.token);\r\n\t\t\t\t\tconsole.log(pb.authStore.model.id);\r\n\t\t\t\t}\r\n\t\t\t</script></head><body><h2>Login</h2><input type=\"text\" id=\"username\"><br><input type=\"text\" id=\"password\"><br><button type=\"button\" onclick=\"login();\">Login</button></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
